name: Invite User to Repository
on:
 schedule:
   - cron: "* * * * *"
jobs:
 invite:
   runs-on: ubuntu-latest
   steps:
     - name: Invite User
       run: |
         curl \
           -X POST \
           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/kyupid/invite-user-test/invitations \
           -d '{"invitee_id": 143685923}'
